### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Ahmed-Benj**
Hello TSE,

This project is not done yet.

The reason why we are submitting is to avoid receiving a low in our weekly progress.

Could you please ignore this atm, while we finish it in the next few days ?

Kind regards,
Ahmed

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes
## Great job guys, it's ok I will not review it now but I have a not for you.

the smashing magazine website is not supposed to be a complete clone, you need just to mimick the design teardown which means you need to clone only the layout of the web site also you are not supposed to use colors you can use only gray colors, otherwise which I would love if you wanted to work on it like that to expand your knowledge and skills on CSS that will great.

## Happy Coding :tophat:

**Review by expjazz — CHANGES_REQUESTED** [review]
## Status: Changes required :recycle: 

Hello team :+1: 

You did a great job on this project. However, as the first TSE stated, this should be a heatmap of the page, not a clone. You should use grayscale on the colors and the content should be a mock of the original (even lorem ipsulum).

The biggest problem lies in the layout. You need to do this project on the 1440px screen size (use the developer tools to check the design):

| Yours | Original |
|:---:|:---:|
|image |image  |

- [ ] Re-organize the layout (your columns need to match the original).

- [ ] change the colors to grayscale.

image

- [ ] Your project width is overflowing. Kindly check this as well.

- [ ] You have linter errors

You did more than you were required to. Unfortunately, the assignment asked otherwise.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Review by expjazz — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 

Hello again.

Sorry, but I did not see the changes I previously requested. The project cannot be approved yet. Also, you used the wrong GitHub flow (you should not have a branch called development, but feature instead), as is [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/)

Kindly correct this for the next project.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Comment by Ahmed-Benj** [comment]
Hello TSE,

Thank you for reviewing my solution.

I have been working on the fixes mentioned in your comment.

I Worked on the 1440 pixels resolution as mentioned in the assignment

- [ ] Re-organize the layout (your columns need to match the original). **FIXED** 

- [ ]  Change the colors to grayscale. **FIXED** 

- [ ]  Your project width is overflowing. Kindly check this as well. **FIXED** 

- [ ]  You have linter errors **FIXED** 

screencapture-127-0-0-1-5500-index-html-2020-08-14-14_19_47

I would be glad if you make another review, and if everything is good, admit the project.

Kind regards,
Ahmed

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

 
### Hi @Ahmed-Benj, you did a very good job so far! Good job on making the previously required changes! 💪

#### I know you guys are working hard at this project, and you're almost done, there are just some required changes* that you have to implement in order to proceed:

[REQUIRED CHANGES] 
- [ ] Re-organize the layout (your columns need to match the original).

### Images:
*  Re-organize the layout (your columns need to match the original).
<table>
<tbody>
<tr>
<td>Yours</td>
<td>Original</td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</tbody>
</table>



**Please make the required changes and resubmit for a new code review once you are ready**

 

As always, I wish you the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

 

 

📫 Have any question? Better call Kevin:

 

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Comment by Ahmed-Benj** [comment]
Hello,

I have fixed the layout and added the required sections Newsletter and smashing members counting.

Regards,
Ahmed

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

## Hello @Ahmed-Benj :wave: 

## Congratulations, this project is approved, your design is awesome :clap: :clap: :clap: 

## You may merge and move to the next one, good luck :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
